AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template for Scrut AWS ECR Integration
Resources:
  ScrutEcrPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: ScrutECRPermission
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - "ecr:GetAuthorizationToken"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:GetRepositoryPolicy"
              - "ecr:DescribeRepositories"
              - "ecr:ListImages"
              - "ecr:DescribeImages"
              - "ecr:BatchGetImage"
              - "ecr:GetLifecyclePolicy"
              - "ecr:GetLifecyclePolicyPreview"
              - "ecr:ListTagsForResource"
              - "ecr:DescribeImageScanFindings"
              - "ecs:ListAccountSettings"
            Resource: "*"
  ScrutECRRole:
    Type: 'AWS::IAM::Role'
    Properties:
      ManagedPolicyArns:
        - !Ref ScrutEcrPolicy
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::123456789:root'
            Condition:
              StringEquals:
                'sts:ExternalId': '123456789'
Outputs:
  RoleARN:
    Description: ARN of the Scrut role
    Value: !GetAtt
      - ScrutECRRole
      - Arn
