AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  UserName:
    Description: "Please enter the name of the user you want to create IAM Role"
    Type: String

Resources:
  MyIAMUser:
    Type: "AWS::IAM::User"
    Properties:
      UserName: !Ref UserName
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/SecurityAudit"
  MyAccessKey:
    Type: "AWS::IAM::AccessKey"
    Properties:
      UserName: !Ref MyIAMUser
      Status: "Active"
  MyAccessKeySecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Description: !Sub "These are the credentials for the IAM User ${MyIAMUser}"
      SecretString: !Join
        - ""
        - - '{"AccessKeyId":"'
          - !Ref MyAccessKey
          - '","SecretAccessKey":"'
          - !GetAtt MyAccessKey.SecretAccessKey
          - '"}'





